version: '3.7'

services:
  ts-node-docker:
    container_name: init-node-docker
    restart: always
    # build:
    #   context: .  
    #   dockerfile: Dockerfile
    #   target: base
    # command: yarn run dev
    # volumes:
    #   - ./src:/usr/src/app/src
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: node dist/server.js
    expose:
      - '3889'
    ports:
      - '3889:3889'